/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 14:30:31,579: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 14:30:31,581: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 14:30:32,589: INFO/MainProcess] mingle: all alone
[2025-09-04 14:30:32,615: INFO/MainProcess] celery@d40239c775b6 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 14:33:36,623: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 14:33:36,624: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 14:33:37,632: INFO/MainProcess] mingle: all alone
[2025-09-04 14:33:37,665: INFO/MainProcess] celery@3fb83d5d4d8e ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 14:39:21,237: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 14:39:21,239: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 14:39:22,246: INFO/MainProcess] mingle: all alone
[2025-09-04 14:39:22,272: INFO/MainProcess] celery@eec816cf01b5 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 14:45:10,546: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 14:45:10,549: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 14:45:11,557: INFO/MainProcess] mingle: all alone
[2025-09-04 14:45:11,582: INFO/MainProcess] celery@59b106940df9 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 14:48:51,591: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 14:48:51,594: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 14:48:52,603: INFO/MainProcess] mingle: all alone
[2025-09-04 14:48:52,625: INFO/MainProcess] celery@6813861bc77a ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 18:50:21,588: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 18:50:21,591: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 18:50:22,597: INFO/MainProcess] mingle: all alone
[2025-09-04 18:50:22,606: INFO/MainProcess] celery@3dc778b5f236 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 18:52:34,017: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 18:52:34,019: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 18:52:35,025: INFO/MainProcess] mingle: all alone
[2025-09-04 18:52:35,039: INFO/MainProcess] celery@641559ff2279 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 18:54:08,469: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 18:54:08,470: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 18:54:09,476: INFO/MainProcess] mingle: all alone
[2025-09-04 18:54:09,485: INFO/MainProcess] celery@e9f99372ad84 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 18:56:18,824: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 18:56:18,826: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 18:56:19,832: INFO/MainProcess] mingle: all alone
[2025-09-04 18:56:19,844: INFO/MainProcess] celery@9fd6be055eee ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 18:59:41,790: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 18:59:41,791: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 18:59:42,797: INFO/MainProcess] mingle: all alone
[2025-09-04 18:59:42,808: INFO/MainProcess] celery@d3de407193f1 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 19:38:11,952: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 19:38:11,955: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 19:38:12,960: INFO/MainProcess] mingle: all alone
[2025-09-04 19:38:12,966: INFO/MainProcess] celery@1b5d0a3af33f ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 19:42:56,031: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 19:42:56,033: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 19:42:57,040: INFO/MainProcess] mingle: all alone
[2025-09-04 19:42:57,048: INFO/MainProcess] celery@c313dc1954ec ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 19:47:55,479: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 19:47:55,480: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 19:47:56,487: INFO/MainProcess] mingle: all alone
[2025-09-04 19:47:56,497: INFO/MainProcess] celery@d4df1404e192 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 19:59:02,363: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 19:59:02,365: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 19:59:03,372: INFO/MainProcess] mingle: all alone
[2025-09-04 19:59:03,385: INFO/MainProcess] celery@db4b49a855ca ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 20:02:39,346: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 20:02:39,350: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 20:02:40,357: INFO/MainProcess] mingle: all alone
[2025-09-04 20:02:40,372: INFO/MainProcess] celery@03b7aa2a1f84 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 20:14:39,902: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 20:14:39,906: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 20:14:40,913: INFO/MainProcess] mingle: all alone
[2025-09-04 20:14:40,922: INFO/MainProcess] celery@ba1d57f79c87 ready.
/usr/local/lib/python3.10/site-packages/django/db/models/base.py:364: RuntimeWarning: Model 'apps_employee.sthstageexperiencelevel' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 21:09:11,295: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 21:09:11,297: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 21:09:12,304: INFO/MainProcess] mingle: all alone
[2025-09-04 21:09:12,315: INFO/MainProcess] celery@618cc5a6d9ad ready.
/usr/local/lib/python3.10/site-packages/django/db/models/base.py:364: RuntimeWarning: Model 'apps_employee.sthstageexperiencelevel' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 21:10:39,208: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 21:10:39,211: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 21:10:40,218: INFO/MainProcess] mingle: all alone
[2025-09-04 21:10:40,234: INFO/MainProcess] celery@dea4990373bf ready.
/usr/local/lib/python3.10/site-packages/django/db/models/base.py:364: RuntimeWarning: Model 'apps_employee.sthstageexperiencelevel' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 21:13:34,998: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 21:13:35,000: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 21:13:36,007: INFO/MainProcess] mingle: all alone
[2025-09-04 21:13:36,018: INFO/MainProcess] celery@16fb6ccfe9db ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-04 21:18:11,454: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-04 21:18:11,456: INFO/MainProcess] mingle: searching for neighbors
[2025-09-04 21:18:12,463: INFO/MainProcess] mingle: all alone
[2025-09-04 21:18:12,475: INFO/MainProcess] celery@678e2e4b7364 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-05 08:57:55,746: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-05 08:57:55,747: INFO/MainProcess] mingle: searching for neighbors
[2025-09-05 08:57:56,755: INFO/MainProcess] mingle: all alone
[2025-09-05 08:57:56,775: INFO/MainProcess] celery@2044820212e3 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-05 09:09:59,527: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-05 09:09:59,528: INFO/MainProcess] mingle: searching for neighbors
[2025-09-05 09:10:00,533: INFO/MainProcess] mingle: all alone
[2025-09-05 09:10:00,540: INFO/MainProcess] celery@ff1470adc695 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-05 09:13:28,682: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-05 09:13:28,684: INFO/MainProcess] mingle: searching for neighbors
[2025-09-05 09:13:29,693: INFO/MainProcess] mingle: all alone
[2025-09-05 09:13:29,702: INFO/MainProcess] celery@93f7b3389c6d ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-07 12:48:58,142: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-07 12:48:58,143: INFO/MainProcess] mingle: searching for neighbors
[2025-09-07 12:48:59,150: INFO/MainProcess] mingle: all alone
[2025-09-07 12:48:59,167: INFO/MainProcess] celery@fffddbcc06a4 ready.
[2025-09-08 06:28:50,183: INFO/MainProcess] Task celery.backend_cleanup[dc42d479-a6b8-4b8b-b39c-0f27f4741d7a] received
[2025-09-08 06:28:50,211: INFO/ForkPoolWorker-15] Task celery.backend_cleanup[dc42d479-a6b8-4b8b-b39c-0f27f4741d7a] succeeded in 0.019596407997596543s: None
[2025-09-08 14:33:57,953: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 915, in <lambda>
    lambda: command(*args, **kwargs),
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 936, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 650, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 341, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 772, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 1359, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 576, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 925, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 935, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 938, in parse_response
    response = self._execute(conn, try_read)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 914, in _execute
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 108, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 916, in <lambda>
    lambda _: self._reconnect(conn),
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 904, in _reconnect
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
[2025-09-08 14:33:57,957: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:392: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2025-09-08 14:33:57,964: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-11 10:03:34,266: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-11 10:03:34,268: INFO/MainProcess] mingle: searching for neighbors
[2025-09-11 10:03:35,278: INFO/MainProcess] mingle: all alone
[2025-09-11 10:03:35,300: INFO/MainProcess] celery@e6c6e154f308 ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-18 10:53:25,063: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-18 10:53:25,067: INFO/MainProcess] mingle: searching for neighbors
[2025-09-18 10:53:26,082: INFO/MainProcess] mingle: all alone
[2025-09-18 10:53:26,108: INFO/MainProcess] celery@4df461f0194a ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-18 10:54:27,167: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-18 10:54:27,169: INFO/MainProcess] mingle: searching for neighbors
[2025-09-18 10:54:28,178: INFO/MainProcess] mingle: all alone
[2025-09-18 10:54:28,211: INFO/MainProcess] celery@4df461f0194a ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-30 11:04:28,986: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-30 11:04:28,988: INFO/MainProcess] mingle: searching for neighbors
[2025-09-30 11:04:29,997: INFO/MainProcess] mingle: all alone
[2025-09-30 11:04:30,021: INFO/MainProcess] celery@22b2f7322bad ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-30 11:06:08,488: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-30 11:06:08,490: INFO/MainProcess] mingle: searching for neighbors
[2025-09-30 11:06:09,497: INFO/MainProcess] mingle: all alone
[2025-09-30 11:06:09,518: INFO/MainProcess] celery@22b2f7322bad ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2025-09-30 11:14:39,480: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-09-30 11:14:39,483: INFO/MainProcess] mingle: searching for neighbors
[2025-09-30 11:14:40,491: INFO/MainProcess] mingle: all alone
[2025-09-30 11:14:40,509: INFO/MainProcess] celery@2dd5ad5cc08a ready.
